// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: csid.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "csid.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace gproto {

namespace {

const ::google::protobuf::EnumDescriptor* MSGID_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_csid_2eproto() {
  protobuf_AddDesc_csid_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "csid.proto");
  GOOGLE_CHECK(file != NULL);
  MSGID_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_csid_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_csid_2eproto() {
}

void protobuf_AddDesc_csid_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\ncsid.proto\022\006gproto*/\n\005MSGID\022\022\n\rCSID_C2"
    "G_PING\020\220N\022\022\n\rCSID_G2C_PING\020\221N", 69);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "csid.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_csid_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_csid_2eproto {
  StaticDescriptorInitializer_csid_2eproto() {
    protobuf_AddDesc_csid_2eproto();
  }
} static_descriptor_initializer_csid_2eproto_;
const ::google::protobuf::EnumDescriptor* MSGID_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MSGID_descriptor_;
}
bool MSGID_IsValid(int value) {
  switch(value) {
    case 10000:
    case 10001:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace gproto

// @@protoc_insertion_point(global_scope)
