// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scsid.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "scsid.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace gproto {
namespace s {

namespace {

const ::google::protobuf::EnumDescriptor* MSGID_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_scsid_2eproto() {
  protobuf_AddDesc_scsid_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "scsid.proto");
  GOOGLE_CHECK(file != NULL);
  MSGID_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_scsid_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_scsid_2eproto() {
}

void protobuf_AddDesc_scsid_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\013scsid.proto\022\010gproto.s*\034\n\005MSGID\022\023\n\016CSID"
    "_L2W_HEART\020\350\007", 53);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "scsid.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_scsid_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_scsid_2eproto {
  StaticDescriptorInitializer_scsid_2eproto() {
    protobuf_AddDesc_scsid_2eproto();
  }
} static_descriptor_initializer_scsid_2eproto_;
const ::google::protobuf::EnumDescriptor* MSGID_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MSGID_descriptor_;
}
bool MSGID_IsValid(int value) {
  switch(value) {
    case 1000:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace s
}  // namespace gproto

// @@protoc_insertion_point(global_scope)
